apiVersion: v1
kind: ConfigMap
metadata:
  name: www-golang
data:
  # Adding new entries here will make them appear as files in the deployment.
  mixer.html: |
    <html><head>
      <meta name="go-import" content="istio.io/mixer git https://github.com/istio/mixer">
      <meta name="go-source" content="istio.io/mixer     https://github.com/istio/mixer https://github.com/istio/mixer/tree/master{/dir} https://github.com/istio/mixer/blob/master{/dir}/{file}#L{line}">
    </head></html>
  manager.html: |
    <html><head>
      <meta name="go-import" content="istio.io/manager git https://github.com/istio/manager">
      <meta name="go-source" content="istio.io/manager     https://github.com/istio/manager https://github.com/istio/manager/tree/master{/dir} https://github.com/istio/manager/blob/master{/dir}/{file}#L{line}">
    </head></html>
  istio.html: |
    <html><head>
      <meta name="go-import" content="istio.io/istio git https://github.com/istio/istio">
      <meta name="go-source" content="istio.io/istio     https://github.com/istio/istio https://github.com/istio/istio/tree/master{/dir} https://github.com/istio/istio/blob/master{/dir}/{file}#L{line}">
    </head></html>
  api.html: |
    <html><head>
      <meta name="go-import" content="istio.io/api git https://github.com/istio/api">
      <meta name="go-source" content="istio.io/api     https://github.com/istio/api https://github.com/istio/api/tree/master{/dir} https://github.com/istio/api/blob/master{/dir}/{file}#L{line}">
    </head></html>
  auth.html: |
    <html><head>
      <meta name="go-import" content="istio.io/auth git https://github.com/istio/auth">
      <meta name="go-source" content="istio.io/auth     https://github.com/istio/auth https://github.com/istio/auth/tree/master{/dir} https://github.com/istio/auth/blob/master{/dir}/{file}#L{line}">
    </head></html>
  pilot.html: |
    <html><head>
      <meta name="go-import" content="istio.io/pilot git https://github.com/istio/pilot">
      <meta name="go-source" content="istio.io/pilot     https://github.com/istio/pilot https://github.com/istio/pilot/tree/master{/dir} https://github.com/istio/pilot/blob/master{/dir}/{file}#L{line}">
    </head></html>
  broker.html: |
    <html><head>
      <meta name="go-import" content="istio.io/broker git https://github.com/istio/broker">
      <meta name="go-source" content="istio.io/broker     https://github.com/istio/broker https://github.com/istio/broker/tree/master{/dir} https://github.com/istio/broker/blob/master{/dir}/{file}#L{line}">
    </head></html>
